package Client.Model.Enums;

public enum Carts {
    aghahaghi,
    ali,
    arcanitereaper,
    ashbringer,
    aylar,
    benyamin,
    blessingoftheancients,
    bloodfury,
    bookofspecters,
    //    cat,
    cookie,
    darkskies,
    faeze,
    fierywaraxe,
    flamestrike,
    gearblade,
    highmastersaman,
    holylight,
    hossein,
    hosseinhima,
    //    javad,
    khashayar,
    lachin,
    learnjavadonic,
    lightforgedblessing,
    matin,
    mobin,
    nima,
    polymorph,
    quiz,
    sandbreath,
    shahryar,
    silversword,
    soroush,
    sprint,
    strengthinnumbers,
    strengthinnumbersdr,
    swarmofcats,
    truesilverchampion,
    yasaman,


}