package Client.Model.Enums;

public enum NeutralCarts {
    aghahaghi,
    ali,
    arcanitereaper,
    ashbringer,
    blessingoftheancients,
    bloodfury,
    bookofspecters,
    //    cat,
    cookie,
    fierywaraxe,
    gearblade,
    highmastersaman,
    holylight,
    hossein,
    hosseinhima,
    //    javad,
    khashayar,
    lachin,
    learnjavadonic,
    lightforgedblessing,
    matin,
    mobin,
    nima,
    silversword,
    soroush,
    sprint,
    strengthinnumbers,
    strengthinnumbersdr,
    swarmofcats,
    truesilverchampion,

}
